# Para acceder al monitor tengo que ir a la url http://<monitor-url>:8989/hystrix
# Luego en el parametro que hay que pasar pasamos la misma url pero http://<monitor-url>:8989/turbine.stream
# Esto es porque turbine me ayuda a ver muchas apps al mismo tiempo
# Si quiero ver una individual tengo que user en ese atributo http://<some-service-url>:<port>/hystrix.stream
endpoints:
  health:
    sensitive: false
info:
  build:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
spring:
  application:
    name: monitor-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8989
turbine:
  aggregator:
  appConfig: service-test #Separar con "," cada microservicio service-test,other-service
  clusterNameExpression: "'default'"
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/