endpoints:
  health:
    sensitive: false
info:
  build:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
spring:
  application:
    name: service-test
  cloud:
    config:
      uri: http://localhost:8888