server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      enable: true
      server:
        git:
          uri: https://3c93c937cde4d1d281fcd899c1b843474d85d65c:x-oauth-basic@github.com/LaMaldicionDeMandos/microservices-demo/
          searchPaths: configuration/service-test
endpoints:
  health:
    sensitive: false
info:
  build:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@