version: '2'
services:
  test-service:
    build: ..
    image: lamaldiciondemandos/tmx-test-service:v1
    ports:
      - "8080:8080"
    environment:
      PROFILE: "development"
      CONFIGSERVER_URI: http://172.17.0.2:8888